name: OIDC

# Run every 15 minutes so we always have a valid OIDC token for clients to use.
on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  oidc:
    permissions:
      # Needed to access the workflow's OIDC identity.
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Retrieve OIDC token
        run: |
          python -m pip install id &&
          python -m id sigstore > ./oidc-token.txt
      - name: Upload OIDC token artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: oidc-token
          path: ./oidc-token.txt
