name: OIDC

# Run every 15 minutes so we always have a valid OIDC token for clients to use.
on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  oidc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Retrieve OIDC token
        run: |
          python -m pip install id &&
          python -m id sigstore
