name: OIDC

# Listen for workflow dispatch events from client repositories.
on: workflow_dispatch

jobs:
  oidc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Retrieve OIDC token
        run: |
          python -m pip install id &&
          python -m id sigstore
